In [14]:
import numpy as np
import torch
import torch.nn.functional as F

In [28]:
img_features = np.random.randn(10,256)
txt_features = np.random.randn(10,256)
img_centroids = np.random.randn(2,256)

sim_img = torch.from_numpy(img_features @ img_centroids.T)
self_sim_img = torch.from_numpy(np.sum(img_features * txt_features,axis=1,keepdims=True))

print(sim_img.shape)
print(self_sim_img.shape)
# print(sim_img)

loss1 = torch.mean(-1*torch.log(torch.exp(sim_img - self_sim_img).sum(axis=1,keepdims=True)))


sim_img2 = torch.from_numpy(np.concatenate([sim_img,self_sim_img],axis=1))
class_probs = np.zeros_like(sim_img2)
class_probs[:,-1]=1
class_probs = torch.from_numpy(class_probs)

labels = torch.ones(sim_img2.shape[0],dtype=torch.int64)*sim_img2.shape[1]-1

loss2 = F.cross_entropy(sim_img2, class_probs)
loss3 = F.cross_entropy(sim_img2, labels)

print(loss1)
print(loss2)
print(loss3)

torch.Size([10, 2])
torch.Size([10, 1])
tensor(-17.5499, dtype=torch.float64)
tensor(19.7593, dtype=torch.float64)
tensor(19.7593, dtype=torch.float64)


In [30]:
mask_neg = torch.ones((10,3))
mask_neg[:,-1] = 0
print(mask_neg)

tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]])


In [31]:
1-torch.eye(10)

tensor([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

array([247.63140518, 260.89759413, 271.71672185, 281.01691447,
       262.26222091, 257.57701624, 249.95972223, 243.79764167,
       263.63449606, 255.61284565])